### ISSUE TITLE
SQL Updater cannot execute function creations

### ISSUE THREAD

**Issue by Simzahn001** [rainbowdashlabs/sadu#124]
If you try to execute a patch file (e.g. patch_2.sql), which contains a `CREATE FUNCTION` statement, it does not work. An SQL Syntax Error is thrown. 
When the statement is executed via the command line, it does work perfectly fine.
Neither when running with using other Delimiters, nor without them does work.

Here is the statement I ran into this issue with: [GIST](https://gist.github.com/Simzahn001/d0aa8e14ba69c1e7576ac5c8525838e8)
Setup when the issue first occurred:
 - Database: MariaDB
 - Program, which uses the SADU Updater: A PaperMC plugin executed on MC version 1.19.4; Java version 17
Tested with:
 - Standalone java application on java 17, java 20, java 8
 - Simpler `CREATE FUNCTIONS` with just a simple statement inside
All Tests performed on Server running on Debian 12.0 (Debian 12.1 not tested)

Solution I use for now:
Just remove the `CREATE FUNCTION` statements from the patch file and add them manually xD

**Comment by rainbowdashlabs** [comment]
What is the error message you get from MariaDB.

**Comment by Simzahn001** [comment]
Can't we just search for the keyword "DELIMITER" in the query strings and use the new delimiter as a regex until a new "DELIMITER" keyword is found?
This may be a little bit more work, but definitely enhances the user experience. The user of SADU would not have to care about using specific delimiters and can just write their statements as they are used to.

**Comment by rainbowdashlabs** [comment]
I cant really imagine how this would look like inside the upgrade script. Can you give an example?

**Comment by Simzahn001** [comment]
I've pushed an approach I worked out to the branch "main/feature/patch-statements-error". What do you think about it?
