### ISSUE TITLE
Replace VersionInfo with SqlVersion

### ISSUE THREAD

**Issue by RainbowDashLabs** [RainbowDashLabs/sadu#21]
We have two very similar classes called VersionInfo and SqlVersion. Both are used in the SqlUpdater. While SqlVersion is used in external calls by other users, the VersionInfo exists purely for internal use.

Replace usage of VersionInfo with SqlVersion and remove the class.

Affected Modules:
- sadu-updater

**Comment by BaLiKfromUA** [comment]
Hey! I would be happy to solve this issue in the scope of Hactoberfest 2022. Can you assign it to me, and I will send my solution during October?

**Comment by RainbowDashLabs** [comment]
Please only claim one issue at a time ^^ You can claim the next one once you proposed your solution ^^

**Comment by BaLiKfromUA** [comment]
Okay, got you.  Can you assign this one to me?
