### ISSUE TITLE
Add support for java date time api

### ISSUE THREAD

**Issue by rainbowdashlabs** [rainbowdashlabs/sadu#22]
Add support for the java [date time api](https://docs.oracle.com/javase/8/docs/technotes/guides/datetime/index.html) introduced in java 8 in the Row and ParamBuilder.

At least for:
- [x] LocalDate
- [x] LocalTime
- [x] LocalDateTime
- [x] Instant (Make sure that it is used as a unix timestamp)
- [x] ZonedDateTime
- [x] OffsetDateTime
- [x] OffsetTime
- [x] Unix Timestamp (Important for databases without a date or timestamp type like SqLite)

Additionally add support to add a current timestamp. Can be simply a delegate to the instant call.

Affected Modules:
- sadu-mapper
- sadu-queries

**Comment by BaLiKfromUA** [comment]
Hey! I would be happy to solve this issue in the scope of Hactoberfest 2022. Can you assign it to me, and I will send my solution in October?
