### ISSUE TITLE
Replace Runtime exteptions with proper implementation

### ISSUE THREAD

**Issue by RainbowDashLabs** [RainbowDashLabs/sadu#23]
In DataSourceCreater#loadDriverClass we wrap a exceptions in a runtime exception. This should be replaced by an own exception since usage of the RuntimeException class is not a good practice.

Affected Modules:
- sadu-datasource

**Comment by BaLiKfromUA** [comment]
Hey! I would be happy to solve this issue in the scope of Hactoberfest 2022. Can you assign it to me, and I will send my solution in October?
