### ISSUE TITLE
Saidu idi talle
Computer Cyber Security 
Information security Computer security Student at NITDA Blockchain technology

### ISSUE THREAD

**Issue by TalleA15** [RainbowDashLabs/sadu#44]
https://github.com/favour-22/NITDA_personal_javascript_learning/tree/main/Data_types

**Comment by TalleA15** [comment]
To add to numbers in a java example!!

Int a = 20; 
Int b = 30; 
Int a+b = result;
System.out.println("result");

**Comment by RainbowDashLabs** [comment]
What is the actual purpose of this issue?

**Comment by TalleA15** [comment]
approve
