### ISSUE TITLE
NullPointerError

### ISSUE THREAD

**Issue by Baaasty** [rainbowdashlabs/sadu#49]
Also in der Doku steht NULL or UUID yk?
Aber das ist nur UUID oder Error. Bitte fixen 💃🏼 i need that

https://github.com/rainbowdashlabs/sadu/blob/3890aedc8108238f6e06f9faaa4488f8da895289/sadu-mapper/src/main/java/de/chojo/sadu/wrapper/util/Row.java#L589

**Comment by yannicklamprecht** [comment]
d92e0d826bcbf373eca0abfcd6c39d431e63fc0b
